/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package virtualAgenda;

import virtualAgenda.view.LoginView;

public class App {

    public static void main(String[] args) {
        
        new LoginView().setVisible(true);
    }
}
