/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package virtualAgenda.view;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import virtualAgenda.controller.AgendaController;
import virtualAgenda.controller.UserController;

/**
 *
 * @author FELIPECANTINI
 */
public class AgendaView extends javax.swing.JFrame {

    /**
     * Creates new form AgendaView
     */
    
    UserController userController = new UserController();
    AgendaController agendaController = new AgendaController();
    
    private DefaultListModel<String> listModel;
    
    public AgendaView(String idUser, String username) {
        initComponents();
        
        listModel = new DefaultListModel<>();
        agendaList.setModel(listModel);
        
        txtIdUser.setText(idUser);
        txtWelcome.setText(username + "'s agenda");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        agendaList = new javax.swing.JList<>();
        hourBox = new javax.swing.JComboBox<>();
        dayBox = new javax.swing.JComboBox<>();
        monthBox = new javax.swing.JComboBox<>();
        txtName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnList = new javax.swing.JButton();
        txtIdUser = new javax.swing.JLabel();
        txtWelcome = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(agendaList);

        hourBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00:00  ", "00:15  ", "00:30  ", "00:45  ", "01:00  ", "01:15  ", "01:30  ", "01:45  ", "02:00  ", "02:15  ", "02:30  ", "02:45  ", "03:00  ", "03:15  ", "03:30  ", "03:45  ", "04:00  ", "04:15  ", "04:30  ", "04:45  ", "05:00  ", "05:15  ", "05:30  ", "05:45  ", "06:00  ", "06:15  ", "06:30  ", "06:45  ", "07:00  ", "07:15  ", "07:30  ", "07:45  ", "08:00  ", "08:15  ", "08:30  ", "08:45  ", "09:00  ", "09:15  ", "09:30  ", "09:45  ", "10:00  ", "10:15  ", "10:30  ", "10:45  ", "11:00  ", "11:15  ", "11:30  ", "11:45  ", "12:00  ", "12:15  ", "12:30  ", "12:45  ", "13:00  ", "13:15  ", "13:30  ", "13:45  ", "14:00  ", "14:15  ", "14:30  ", "14:45  ", "15:00  ", "15:15  ", "15:30  ", "15:45  ", "16:00  ", "16:15  ", "16:30  ", "16:45  ", "17:00  ", "17:15  ", "17:30  ", "17:45  ", "18:00  ", "18:15  ", "18:30  ", "18:45  ", "19:00  ", "19:15  ", "19:30  ", "19:45  ", "20:00  ", "20:15  ", "20:30  ", "20:45  ", "21:00  ", "21:15  ", "21:30  ", "21:45  ", "22:00  ", "22:15  ", "22:30  ", "22:45  ", "23:00  ", "23:15  ", "23:30  ", "23:45  " }));

        dayBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01  ", "02  ", "03  ", "04  ", "05  ", "06  ", "07  ", "08  ", "09  ", "10  ", "11  ", "12  ", "13  ", "14  ", "15  ", "16  ", "17  ", "18  ", "19  ", "20  ", "21  ", "22  ", "23  ", "24  ", "25  ", "26  ", "27  ", "28  ", "29  ", "30  ", "31" }));

        monthBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "09", "09", "10", "11", "12" }));

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnList.setText("List");
        btnList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListActionPerformed(evt);
            }
        });

        txtIdUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIdUser.setText("jLabel1");

        txtWelcome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtWelcome.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtIdUser)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtWelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(hourBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dayBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(monthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)))
                .addGap(167, 167, 167))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(txtWelcome)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hourBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dayBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnList))
                .addGap(18, 18, 18)
                .addComponent(txtIdUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        
        String name = txtName.getText();
        
        String idUserString = txtIdUser.getText();
        int idUser = Integer.parseInt(idUserString);
        
        Object day = dayBox.getSelectedItem();
        String dayString = day.toString().trim();
        
        Object month = monthBox.getSelectedItem();
        String monthString = month.toString().trim();
        
        Object hour = hourBox.getSelectedItem();
        String hourString = hour.toString().trim();
        
        String date = dayString + "/" + monthString;
        
        String message = agendaController.addAgenda(name, idUser, date, hourString);
        JOptionPane.showMessageDialog(this, message);
        
        if (message.equals("Succesfully added")) {
            txtName.setText("");
        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListActionPerformed
        // TODO add your handling code here:
        
        listModel.clear();
        
        String idUserString = txtIdUser.getText();
        int idUser = Integer.parseInt(idUserString);
        
        ArrayList<String> listAgenda = agendaController.listAgenda(idUser);
        
        for (String agenda : listAgenda){
            listModel.addElement(agenda);
        }
    }//GEN-LAST:event_btnListActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        int index = agendaList.getSelectedIndex();
        
        String idUserString = txtIdUser.getText();
        int idUser = Integer.parseInt(idUserString);
        
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Select a row!");
            return;
        }
        
        String message = agendaController.deleteAgenda(index, idUser);
        JOptionPane.showMessageDialog(this, message);
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
        String newName = txtName.getText();
        
        String idUserString = txtIdUser.getText();
        int idUser = Integer.parseInt(idUserString);
        
        Object day = dayBox.getSelectedItem();
        String dayString = day.toString().trim();
        
        Object month = monthBox.getSelectedItem();
        String monthString = month.toString().trim();
        
        Object hour = hourBox.getSelectedItem();
        String newHourString = hour.toString().trim();
        
        String newDate = dayString + "/" + monthString;
        
        int index = agendaList.getSelectedIndex();
        
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Select a row!");
            return;
        }
        
        String message = agendaController.updateAgenda(index, idUser, newName, newDate, newHourString);
        JOptionPane.showMessageDialog(this, message);
        
         if (message.equals("Succesfully updated")) {
            txtName.setText("");
        }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgendaView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgendaView("idUser", "username").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> agendaList;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnList;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> dayBox;
    private javax.swing.JComboBox<String> hourBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> monthBox;
    private javax.swing.JLabel txtIdUser;
    private javax.swing.JTextField txtName;
    private javax.swing.JLabel txtWelcome;
    // End of variables declaration//GEN-END:variables
}
